var es = require('child_process').execSync;

// require('epipebomb')();

var cl_decode_valid = 16;
var cl_encode_valid = 32;

var brands = {
    '2wire': '2Wire',
    '3m': '3M',
    // 'abit': 'abit',
    // 'abs': 'abs',
    'accesshd': 'Access HD',
    'accessmedia': 'Access Media',
    'acer': 'Acer',
    'aconatic': 'Aconatic',
    'acorp': 'ACoRP',
    'adaptec': 'Adaptec',
    // 'adb': 'adb',
    'admiral': 'Admiral',
    'ads': 'ADS',
    'adstech': 'ADS Tech',
    // 'advanced_acoustic': 'advanced_acoustic',
    // 'aim': 'aim',
    // 'aiwa': 'aiwa',
    // 'akai': 'akai',
    // 'aki': 'aki',
    // 'alba': 'alba',
    // 'allsat': 'allsat',
    // 'alpine': 'alpine',
    // 'amino': 'amino',
    // 'amstrad': 'amstrad',
    // 'amytel': 'amytel',
    // 'animax': 'animax',
    // 'anitech': 'anitech',
    // 'anysee': 'anysee',
    // 'aoc': 'aoc',
    // 'aopen': 'aopen',
    // 'apex': 'apex',
    // 'apple': 'apple',
    // 'arcam': 'arcam',
    // 'aristona': 'aristona',
    // 'askey': 'askey',
    // 'aspire_digital': 'aspire_digital',
    // 'astro': 'astro',
    // 'asus': 'asus',
    // 'aten': 'aten',
    // 'atiusb': 'atiusb',
    // 'atlanta_dth': 'atlanta_dth',
    // 'atlas': 'atlas',
    // 'att': 'att',
    // 'audiosonic': 'audiosonic',
    // 'audiosource': 'audiosource',
    // 'audiovox': 'audiovox',
    // 'aureal': 'aureal',
    // 'autumnwave': 'autumnwave',
    // 'auvisio': 'auvisio',
    // 'avermedia': 'avermedia',
    // 'avex': 'avex',
    // 'avtoolbox': 'avtoolbox',
    // 'awlibusb': 'awlibusb',
    // 'axion': 'axion',
    // 'azbox': 'azbox',
    // 'bang&olufsen': 'bang&olufsen',
    // 'barco': 'barco',
    // 'bbk': 'bbk',
    // 'beko': 'beko',
    // 'belkin': 'belkin',
    // 'bellagio': 'bellagio',
    // 'bench': 'bench',
    // 'benq': 'benq',
    // 'beon': 'beon',
    // 'bestbuy': 'bestbuy',
    // 'blaupunkt': 'blaupunkt',
    // 'bluesky': 'bluesky',
    // 'bork': 'bork',
    // 'bose': 'bose',
    // 'brondell': 'brondell',
    // 'bush': 'bush',
    // 'cambridge_audio': 'cambridge_audio',
    // 'canalsat': 'canalsat',
    // 'canon': 'canon',
    // 'captain': 'captain',
    // 'captiveworks': 'captiveworks',
    // 'caraca': 'caraca',
    // 'casio': 'casio',
    // 'cat': 'cat',
    // 'cce': 'cce',
    // 'cenOmax': 'cenOmax',
    // 'centrum': 'centrum',
    // 'century_concept': 'century_concept',
    // 'chaparral': 'chaparral',
    // 'chinon': 'chinon',
    // 'chiro': 'chiro',
    // 'chronos': 'chronos',
    // 'ciat': 'ciat',
    // 'cisco': 'cisco',
    // 'citizen': 'citizen',
    // 'clarion': 'clarion',
    // 'comag': 'comag',
    // 'comcast': 'comcast',
    // 'commodore': 'commodore',
    // 'compro': 'compro',
    // 'conrad': 'conrad',
    // 'contour': 'contour',
    // 'coolsat': 'coolsat',
    // 'cosmel': 'cosmel',
    // 'cox': 'cox',
    // 'cph03x': 'cph03x',
    // 'creative': 'creative',
    // 'crown': 'crown',
    // 'cttc': 'cttc',
    // 'curtis_electronics': 'curtis_electronics',
    // 'cyberhome': 'cyberhome',
    // 'cypress': 'cypress',
    // 'd-link': 'd-link',
    // 'daeumling': 'daeumling',
    // 'daewoo': 'daewoo',
    // 'dantax': 'dantax',
    // 'dart_europe': 'dart_europe',
    // 'daytron': 'daytron',
    // 'dell': 'dell',
    // 'denon': 'denon',
    // 'denver': 'denver',
    // 'devinput': 'devinput',
    // 'difrnce': 'difrnce',
    // 'digital_stream': 'digital_stream',
    // 'directv': 'directv',
    // 'dishnet': 'dishnet',
    // 'dk_digital': 'dk_digital',
    // 'domland': 'domland',
    // 'dream_multimedia': 'dream_multimedia',
    // 'dse': 'dse',
    // 'dual': 'dual',
    // 'durabrand': 'durabrand',
    // 'dvico': 'dvico',
    // 'dynaudio': 'dynaudio',
    // 'dynex': 'dynex',
    // 'e-tech': 'e-tech',
    // 'ea65': 'ea65',
    // 'eagle_aspen': 'eagle_aspen',
    // 'echostar': 'echostar',
    // 'eclipse': 'eclipse',
    // 'ecotel': 'ecotel',
    // 'ei': 'ei',
    // 'elenberg': 'elenberg',
    // 'elite': 'elite',
    // 'elitron': 'elitron',
    // 'elmak': 'elmak',
    // 'elmo': 'elmo',
    // 'eltasat': 'eltasat',
    // 'eltax': 'eltax',
    // 'emerson': 'emerson',
    // 'entone': 'entone',
    // 'epson': 'epson',
    // 'ericsson': 'ericsson',
    // 'euroconsumers': 'euroconsumers',
    // 'evation': 'evation',
    // 'expressvu': 'expressvu',
    // 'fagor': 'fagor',
    // 'falcon': 'falcon',
    // 'fenner': 'fenner',
    // 'ferguson': 'ferguson',
    // 'finlux': 'finlux',
    // 'fisher': 'fisher',
    // 'fisher_price': 'fisher_price',
    // 'fortec': 'fortec',
    // 'fox': 'fox',
    // 'foxtel': 'foxtel',
    // 'frahm': 'frahm',
    // 'free': 'free',
    // 'freecom': 'freecom',
    // 'freedomland': 'freedomland',
    // 'fresat': 'fresat',
    // 'fte_maximal': 'fte_maximal',
    // 'fuba': 'fuba',
    // 'fujitsu': 'fujitsu',
    // 'fujitsu_siemens': 'fujitsu_siemens',
    // 'fujtech': 'fujtech',
    // 'funai': 'funai',
    // 'furby': 'furby',
    // 'galaxis': 'galaxis',
    // 'gamefactory': 'gamefactory',
    // 'ge': 'ge',
    // 'general': 'general',
    // 'general_instrument': 'general_instrument',
    // 'generic': 'generic',
    // 'geniatech': 'geniatech',
    // 'genius': 'genius',
    // 'genus': 'genus',
    // 'get': 'get',
    // 'gigabyte': 'gigabyte',
    // 'golden_interstart': 'golden_interstart',
    // 'goldstar': 'goldstar',
    // 'goodmans': 'goodmans',
    // 'govideo': 'govideo',
    // 'gradiente': 'gradiente',
    // 'graetz': 'graetz',
    // 'grandin': 'grandin',
    // 'gran_prix': 'gran_prix',
    // 'grundig': 'grundig',
    // 'guillemot': 'guillemot',
    // 'gvc': 'gvc',
    // 'hama': 'hama',
    // 'hampton_bay': 'hampton_bay',
    // 'harman_kardon': 'harman_kardon',
    // 'harting_helling': 'harting_helling',
    // 'hauppauge': 'hauppauge',
    // 'hb': 'hb',
    // 'hello_kitty': 'hello_kitty',
    // 'hercules': 'hercules',
    // 'hermstedt': 'hermstedt',
    // 'hinen_electronics': 'hinen_electronics',
    // 'hip_interactive': 'hip_interactive',
    // 'hirschmann': 'hirschmann',
    // 'hitachi': 'hitachi',
    // 'hivion': 'hivion',
    // 'hokkaido': 'hokkaido',
    // 'holtek': 'holtek',
    // 'homecast': 'homecast',
    // 'hometech': 'hometech',
    // 'home_cable': 'home_cable',
    // 'horizont': 'horizont',
    // 'hot': 'hot',
    // 'hp': 'hp',
    // 'hq': 'hq',
    // 'hughes': 'hughes',
    // 'humax': 'humax',
    // 'huth': 'huth',
    // 'hyundai': 'hyundai',
    // 'i24': 'i24',
    // 'ibm': 'ibm',
    // 'ice': 'ice',
    // 'illusion': 'illusion',
    // 'images': 'images',
    // 'imex': 'imex',
    // 'imon': 'imon',
    // 'infocus': 'infocus',
    // 'insignia': 'insignia',
    // 'interact': 'interact',
    // 'intervision': 'intervision',
    // 'iodata': 'iodata',
    // 'ione': 'ione',
    // 'irlink': 'irlink',
    // 'irobot': 'irobot',
    // 'irradio': 'irradio',
    // 'isp': 'isp',
    // 'italtel': 'italtel',
    // 'itt': 'itt',
    // 'itv_media': 'itv_media',
    // 'jbl': 'jbl',
    // 'jerrold': 'jerrold',
    // 'jvc': 'jvc',
    // 'kanam_accent': 'kanam_accent',
    // 'kaon': 'kaon',
    // 'kathrein': 'kathrein',
    // 'kawa': 'kawa',
    // 'kendo': 'kendo',
    // 'kenmore': 'kenmore',
    // 'kenwood': 'kenwood',
    // 'khl': 'khl',
    // 'kingman': 'kingman',
    // 'kiss': 'kiss',
    // 'knc_one': 'knc_one',
    // 'kodak': 'kodak',
    // 'konig': 'konig',
    // 'konka': 'konka',
    // 'korting': 'korting',
    // 'kosmos': 'kosmos',
    // 'kworld': 'kworld',
    // 'l&s_electronic': 'l&s_electronic',
    // 'l+s': 'l+s',
    // 'lacie': 'lacie',
    // 'lasonic': 'lasonic',
    // 'leadership': 'leadership',
    // 'leadtek': 'leadtek',
    // 'lemon': 'lemon',
    // 'lenco': 'lenco',
    // 'lenovo': 'lenovo',
    // 'lexicon': 'lexicon',
    // 'lg': 'lg',
    // 'life-view': 'life-view',
    // 'lifesat': 'lifesat',
    // 'lifetec': 'lifetec',
    // 'linksys': 'linksys',
    // 'loewe': 'loewe',
    // 'logitech': 'logitech',
    // 'lpi': 'lpi',
    // 'lutron': 'lutron',
    // 'luxor': 'luxor',
    // 'm3_electronic': 'm3_electronic',
    // 'macro_image_technology': 'macro_image_technology',
    // 'magnasonic': 'magnasonic',
    // 'magnavox': 'magnavox',
    // 'magnum': 'magnum',
    // 'majestic': 'majestic',
    // 'manhattan': 'manhattan',
    // 'manta': 'manta',
    // 'marantz': 'marantz',
    // 'mark': 'mark',
    // 'mas': 'mas',
    // 'mbo': 'mbo',
    // 'mceusb': 'mceusb',
    // 'mcl': 'mcl',
    // 'media-tech': 'media-tech',
    // 'medion': 'medion',
    // 'megatron': 'megatron',
    // 'melectronic': 'melectronic',
    // 'meliconi': 'meliconi',
    // 'meridian': 'meridian',
    // 'metronic': 'metronic',
    // 'metz': 'metz',
    // 'microsoft': 'microsoft',
    // 'minolta': 'minolta',
    // 'miro': 'miro',
    // 'mitaki': 'mitaki',
    // 'mitochiba': 'mitochiba',
    // 'mitsubishi': 'mitsubishi',
    // 'mivar': 'mivar',
    // 'moneual': 'moneual',
    // 'monoprice': 'monoprice',
    // 'morgan\'s_daytona': 'morgan\'s_daytona',
    // 'motorola': 'motorola',
    // 'ms-tech': 'ms-tech',
    // 'msi': 'msi',
    // 'mStation': 'mStation',
    // 'multichoice': 'multichoice',
    // 'multitec': 'multitec',
    // 'multi_canal': 'multi_canal',
    // 'mustek': 'mustek',
    // 'mvision': 'mvision',
    // 'nad': 'nad',
    // 'nagra': 'nagra',
    // 'nakamichi': 'nakamichi',
    // 'napa': 'napa',
    // 'national': 'national',
    // 'nebula_electronics': 'nebula_electronics',
    // 'nec': 'nec',
    // 'netgem': 'netgem',
    // 'nextwave': 'nextwave',
    // 'nikko': 'nikko',
    // 'nikon': 'nikon',
    // 'nokia': 'nokia',
    // 'norcent': 'norcent',
    // 'nordmende': 'nordmende',
    // 'northq': 'northq',
    // 'now_broadband_tv': 'now_broadband_tv',
    // 'no_brand': 'no_brand',
    // 'nse': 'nse',
    // 'ntl': 'ntl',
    // 'nubert': 'nubert',
    // 'nvidia': 'nvidia',
    // 'oceanic': 'oceanic',
    // 'octaltv': 'octaltv',
    // 'olevia': 'olevia',
    // 'olympus': 'olympus',
    // 'one_for_all': 'one_for_all',
    // 'onida': 'onida',
    // 'onkyo': 'onkyo',
    // 'optex': 'optex',
    // 'optimus': 'optimus',
    // 'orava': 'orava',
    // 'orava/ovara': 'orava/ovara',
    // 'orion': 'orion',
    // 'oritron': 'oritron',
    // 'osram': 'osram',
    // 'pace': 'pace',
    // 'packard_bell': 'packard_bell',
    // 'palcom': 'palcom',
    // 'palladium': 'palladium',
    // 'palmbutler': 'palmbutler',
    // 'panasat': 'panasat',
    // 'panasonic': 'panasonic',
    // 'panda': 'panda',
    // 'pansat': 'pansat',
    // 'parex': 'parex',
    // 'pcmak': 'pcmak',
    // 'pc_expert_tech': 'pc_expert_tech',
    // 'peekton': 'peekton',
    // 'philco': 'philco',
    // 'philex': 'philex',
    // 'philips': 'philips',
    // 'phonotrend': 'phonotrend',
    // 'pinnacle_systems': 'pinnacle_systems',
    // 'pioneer': 'pioneer',
    // 'pipi': 'pipi',
    // 'pixelview': 'pixelview',
    // 'plu2': 'plu2',
    // 'polaroid': 'polaroid',
    // 'pollin': 'pollin',
    // 'proplay': 'proplay',
    // 'proscan': 'proscan',
    // 'protek': 'protek',
    // 'provideo': 'provideo',
    // 'provision': 'provision',
    // 'q-sonic': 'q-sonic',
    // 'quadral': 'quadral',
    // 'rademacher': 'rademacher',
    // 'radio_shack': 'radio_shack',
    // 'radix': 'radix',
    // 'raite': 'raite',
    // 'ranex': 'ranex',
    // 'rc-5': 'rc-5',
    // 'rca': 'rca',
    // 're.x': 're.x',
    // 'recor': 'recor',
    // 'rega': 'rega',
    // 'remotec': 'remotec',
    // 'replaytv': 'replaytv',
    // 'revo': 'revo',
    // 'revoy': 'revoy',
    // 'rft': 'rft',
    // 'rio': 'rio',
    // 'roadstar': 'roadstar',
    // 'robotron': 'robotron',
    // 'roku': 'roku',
    // 'rolsen': 'rolsen',
    // 'rotel': 'rotel',
    // 'rowa': 'rowa',
    // 'rubin': 'rubin',
    // 'ruwido': 'ruwido',
    // 'sab': 'sab',
    // 'saba': 'saba',
    // 'sagem': 'sagem',
    // 'salora': 'salora',
    // 'samsung': 'samsung',
    // 'samy': 'samy',
    // 'sansonic': 'sansonic',
    // 'sansui': 'sansui',
    // 'sanyo': 'sanyo',
    // 'sasem': 'sasem',
    // 'satelco': 'satelco',
    // 'schneider': 'schneider',
    // 'schwaiger': 'schwaiger',
    // 'scientific_atlanta': 'scientific_atlanta',
    // 'scott': 'scott',
    // 'seg': 'seg',
    // 'seiko': 'seiko',
    // 'sejin_electron': 'sejin_electron',
    // 'sencor': 'sencor',
    // 'sgi': 'sgi',
    // 'shannon': 'shannon',
    // 'sharp': 'sharp',
    // 'sharpsat': 'sharpsat',
    // 'sherwood': 'sherwood',
    // 'shinco': 'shinco',
    // 'shuttle': 'shuttle',
    // 'siemens': 'siemens',
    // 'sigmatek': 'sigmatek',
    // 'sigma_designs': 'sigma_designs',
    // 'silent-gliss': 'silent-gliss',
    // 'silitek': 'silitek',
    // 'silvercrest': 'silvercrest',
    // 'sirius': 'sirius',
    // 'sitronics': 'sitronics',
    // 'sky': 'sky',
    // 'skymaster': 'skymaster',
    // 'slim_art': 'slim_art',
    // 'slim_devices': 'slim_devices',
    // 'smoovietv': 'smoovietv',
    // 'snapstream': 'snapstream',
    // 'snazio': 'snazio',
    // 'solidtek': 'solidtek',
    // 'sonicview': 'sonicview',
    // 'sony': 'sony',
    // 'sonyir': 'sonyir',
    // 'speed-link': 'speed-link',
    // 'st': 'st',
    // 'starhub': 'starhub',
    // 'starsat': 'starsat',
    // 'starview': 'starview',
    // 'streamzap': 'streamzap',
    // 'strong': 'strong',
    // 'sumvision': 'sumvision',
    // 'sun': 'sun',
    // 'sungale': 'sungale',
    // 'supermax': 'supermax',
    // 'supersqny': 'supersqny',
    // 'supportplus': 'supportplus',
    // 'sven': 'sven',
    // 'syabas': 'syabas',
    // 'symphonic': 'symphonic',
    // 'system76': 'system76',
    // 't+a': 't+a',
    // 't-online': 't-online',
    // 'tab_electronics': 'tab_electronics',
    // 'tascam': 'tascam',
    // 'tcm': 'tcm',
    // 'tcuag': 'tcuag',
    // 'teac': 'teac',
    // 'technics': 'technics',
    // 'technisat': 'technisat',
    // 'technoline': 'technoline',
    // 'technosonic': 'technosonic',
    // 'technotrend': 'technotrend',
    // 'teco': 'teco',
    // 'tekram': 'tekram',
    // 'telecom_italia': 'telecom_italia',
    // 'telefunken': 'telefunken',
    // 'teleka': 'teleka',
    // 'telenet': 'telenet',
    // 'televes': 'televes',
    // 'tensai': 'tensai',
    // 'terratec': 'terratec',
    // 'tesla': 'tesla',
    // 'tevii': 'tevii',
    // 'tevion': 'tevion',
    // 'thermaltake': 'thermaltake',
    // 'thinkgeek': 'thinkgeek',
    // 'thompson': 'thompson',
    // 'thomson': 'thomson',
    // 'time_warner_cable': 'time_warner_cable',
    // 'tivii': 'tivii',
    // 'tivo': 'tivo',
    // 'tivoli': 'tivoli',
    // 'tokai': 'tokai',
    // 'topfield': 'topfield',
    // 'topseed': 'topseed',
    // 'toshiba': 'toshiba',
    // 'total_control': 'total_control',
    // 'total_media_in_hand': 'total_media_in_hand',
    // 'traxis': 'traxis',
    // 'triax': 'triax',
    // 'trice': 'trice',
    // 'trio': 'trio',
    // 'trust': 'trust',
    // 'trutech': 'trutech',
    // 'turtlebeach': 'turtlebeach',
    // 'twinhan': 'twinhan',
    // 'typhoon': 'typhoon',
    // 'uec': 'uec',
    // 'uei': 'uei',
    // 'ultrawave': 'ultrawave',
    // 'umax': 'umax',
    // 'uniden': 'uniden',
    // 'united': 'united',
    // 'universal': 'universal',
    // 'universum': 'universum',
    // 'upc': 'upc',
    // 'venturer': 'venturer',
    // 'vestel': 'vestel',
    // 'video7': 'video7',
    // 'videologic': 'videologic',
    // 'viewmaster': 'viewmaster',
    // 'viewmaxpro': 'viewmaxpro',
    // 'viewsat': 'viewsat',
    // 'viewsonic': 'viewsonic',
    // 'virgin-media': 'virgin-media',
    // 'visionetics': 'visionetics',
    // 'vistron': 'vistron',
    // 'vitek': 'vitek',
    // 'vivanco': 'vivanco',
    // 'vizio': 'vizio',
    // 'vlsystem': 'vlsystem',
    // 'voxson': 'voxson',
    // 'watson': 'watson',
    // 'wd': 'wd',
    // 'westinghouse': 'westinghouse',
    // 'wilfa': 'wilfa',
    // 'x10': 'x10',
    // 'xlogic': 'xlogic',
    // 'xms': 'xms',
    // 'xoro': 'xoro',
    // 'xsat': 'xsat',
    // 'xtreamer': 'xtreamer',
    // 'yakumo': 'yakumo',
    // 'yamada': 'yamada',
    // 'yamaha': 'yamaha',
    // 'yamakawa': 'yamakawa',
    // 'yes': 'yes',
    // 'yuan': 'yuan',
    // 'zalman': 'zalman',
    // 'zehnder': 'zehnder',
    // 'zenith': 'zenith',
    // 'zolid': 'zolid',
    // 'zoltrix': 'zoltrix',
    // 'zotac': 'zotac',
    // 'zyxel': 'zyxel',
}

String.prototype.capitalize = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
}

var r;
var keys;
var keynames;

var reset = function() {
    // try { console.log('moveon'); return; } catch(e) {}
    r = {};
    keys = [];
    keynames = {};
    clevels = [];
}

var set = function(k, v) {
    r[k] = v;
}

var end = function() {
    if (keys.length < 1) r.error = 'no keys';

    var record = {
        // brand: brands[brand] || brand.toUpperCase().replace(/_/g, ' '),
        brand: brand.replace(/_/g, ' '),
        model: model.replace(/_/g, ' '),
    }
    if (r.error)
        record['error'] = r.error;
    else {
        record['name'] = r.name;

        var confidence = 0;
        for (var i = 0; i < keys.length; i++)
            confidence += keys[i].confidence;
        confidence /= keys.length;
        record['confidence'] = Math.floor(confidence + 0.5);

        record['keys'] = keys;
    }
    console.log(JSON.stringify(record));
}

var encodeir = function(p, d, s, f, t) {;
    // console.log('encodeirz ' + p + ' ' + d + ' ' + s + ' ' + f + ' ' + (t || 0));
    return JSON.parse(es('encodeirz ' + p + ' ' + d + ' ' + s + ' ' + f + ' ' + (t || 0)).toString().trim());
}

var key = function(k, p, d, s, f, m, pronto) {
    if (r.error) return;

    // consider only first entry for multiple key definitions
    if (keynames[k] !== undefined) return;
    keynames[k] = 1;

    var record = {
        key: k,
        spec: {
            protocol: p,
            device: d,
            subdevice: s,
            obc: f,
            misc: m
        }
    };
    var clevel = 0;

    // Process protocol string for correct encoding
    p = p.replace(/ /g,'');
    p = p.replace(/{[12]}/,'');
    p = p.replace(/Dish_Network/,'DishPlayer_Network');
    p = p.replace(/G.I.Cable/,'GI_cable');
    p = p.replace(/G.I.4DTV/,'GI4dtv');

    var args = p + ' ' + d + ' ' + s + ' ' + f;
    var ez = encodeir(p, d, s, f, 0);
    if (ez.error === undefined) {
        record['code'] = ez;
        clevel += cl_encode_valid;
        if (m.match(/T=/))
            record['tcode'] = encodeir(p, d, s, f, 1);
    } else {
        pronto = pronto.split(' ');
        var val = [];
        for (var i = 0; i < pronto.length; i++)
            val.push(parseInt(pronto[i], 16));
        if (val[0] !== 0)
            r.error = 'non-zero pronto code';
        else {
            var freqK = 1000 / val[1] / 0.241246; // kHz
            var sng = 2 * val[2],
                rpt = 2 * val[3];
            if (rpt == 0) {
                rpt = sng;
                sng = 0;
            }
            var seq = [];
            for (var i = 4; i < val.length; i++)
                seq.push(val[i]);
            record['code'] = {
                frequency: freqK * 1000,
                n: sng + rpt,
                repeat: [0, sng, sng + rpt],
                seq: seq
            };
        }
    }

    record['confidence'] = clevel;
    keys.push(record);
}

module.exports = {
    reset: reset,
    set: set,
    end: end,
    key: key
}
